### ISSUE TITLE
Bug : The craft event isn't detected

### ISSUE THREAD

**Issue by iambibi** [WolfyScript/viewportl#122]
Hi, I have a BeautyQuests plugin which allows you to do quests with different events including the Craft of an item, 
In version v4.17-beta.3 of Wolfy Utils and v4.16.9.1 of CustomCrafting, this craft event worked and detected the Craft of the Gold item with the new update of Wolfy Utils, v4.17-beta.4 this does not detect the event.

Without the Bug : 
https://youtu.be/JwU0pNVlx_4
v4.17-beta.3 of Wolfy Utils 
v4.16.9.1 of CustomCrafting
minecraft 1.20.1 paper build 196

https://youtu.be/GmwfKvUSMNw
**v4.17-beta.4 of Wolfy Utils**
v4.16.9.1 of CustomCrafting
minecraft 1.20.1 paper build 196

I think the new Wolfy Utilities update removed something that allows you to detect an event

**Comment by iambibi** [comment]
Is this bug patched soon?

**Comment by iambibi** [comment]
The bug with the new CustomCrafting (v4.16.10) update did not fix the bug

**Comment by WolfyScript** [comment]
It might be an coincidence that it worked before. Custom recipes are usually not easily recognised by other plugins.

I have to add an event that is called when a player crafts an item, so other plugins can use that to detect when recipes are crafted.
I'll link this to WolfyScript/CustomCrafting#354, which is basically a request for this exact thing.
